server:
  port: 8082
spring:
  datasource:
    password: 123
    url: jdbc:postgresql://localhost:5432/nikola
    username: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgresPlusDialect
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
